version: '1'
services:
  training:
    build:
      context: .
      dockerfile: dockers/Dockerfile.training
    ports:
      - "5000:5009"

  inference:
    build:
      context: .
      dockerfile: dockers/Dockerfile.inference
    ports:
      - "5001:5009"

  data_receptor:
    build:
      context: .
      dockerfile: dockers/Dockerfile.data_receptor
    ports:
      - "5002:5009"

  adversarial_generator:
    build:
      context: .
      dockerfile: dockers/Dockerfile.adversarial_generator
    ports:
      - "5003:5009"

  adversarial_discriminator:
    build:
      context: .
      dockerfile: dockers/Dockerfile.adversarial_discriminator
    ports:
      - "5004:5009"

  resilience_verificator:
    build:
      context: .
      dockerfile: dockers/Dockerfile.resilience_verificator
    ports:
      - "5005:5009"
