FROM python:3.10

WORKDIR Analytics
COPY . .

RUN echo pwd
RUN python setup.py sdist bdist_wheel
RUN pip install .
RUN pip install -r requirements.txt


EXPOSE 5000
CMD ["python", "/Analytics/apis/training_aas.py"]