FROM python:3.10

WORKDIR Analytics
COPY . .

RUN echo pwd
RUN python setup.py sdist bdist_wheel
RUN pip install .
RUN pip install -r requirements.txt


EXPOSE 5001
CMD ["python", "/Analytics/apis/inference_aas.py"]